# SPDX-FileCopyrightText: 2021-2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: CC0-1.0
version: 2
updates:
- package-ecosystem: composer
  directories:
  - /
  - /vendor-bin/cs-fixer
  - /vendor-bin/phpunit
  - /vendor-bin/psalm
  - /vendor-bin/rector
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  cooldown:
    default-days: 10
  labels:
    - "3. to review"
    - "dependencies"
  reviewers:
    - "ArtificialOwl"
    - "cristianscheid"

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  cooldown:
    default-days: 10
  open-pull-requests-limit: 10
  labels:
    - "3. to review"
    - "dependencies"
  reviewers:
    - "ArtificialOwl"
    - "cristianscheid"
